# Generated by Django 5.1.1 on 2024-11-19 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="avatar",
            field=models.ImageField(
                blank=True,
                help_text="Загрузите Ваше фото",
                null=True,
                upload_to="media/users/avatars/",
                verbose_name="Аватар",
            ),
        ),
    ]
